replicaCount: 1

image:
  repository: cr.lermanonline.com/test
  tag: "0.1"

ingress:
  enabled: true

configMap:
  config:
    config.properties: |+
        HEALTHY_HOST=healthy-chart
        HEALTHY_PORT=8080
